[build]
  command = "npm run build"

[[plugins]]
  package = "@netlify/plugin-nextjs"
[[plugins]]
  package = "netlify-plugin-cache-nextjs"

  [[redirects]]
  from = "/*"
  to = "/404/index.html"
  status = 404
